//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelID { get; set; }
        public string PersonelAdi { get; set; }
        public string PersonelSoyadi { get; set; }
        public string PersonelAdresi { get; set; }
        public int BirimID { get; set; }
    
        public virtual Birimler Birimler { get; set; }
    }
}
